<?= $this->fetch('header.phtml') ?>
  <form method="POST" action="/devices/<?= e($device['id']) ?>">
    <input type="hidden" name="_METHOD" value="put">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">検証機名編集</h2>
        <div class="card-text">
          <div class="form-group">
            <label for="subject">検証機名</label>
            <input type="text" name="device_name" id="device_name" class="form-control" value="<?= e($device['device_name']) ?>">
          </div>
        </div>
      </div>
      <div class="card-body">
        <button class="btn btn-primary">更新</button>
      </div>
    </div>
  </form>
<?= $this->fetch('footer.phtml') ?>
