<?= $this->fetch('header.phtml') ?>
    <form method="POST" action="/users">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">ユーザ登録</h2>
          <div class="card-text">
            <div class="form-group">
              <label for="name">ユーザID</label>
              <input type="text" name="name" id="name" class="form-control">
              <label for="name">ユーザ名</label>
              <input type="text" name="user_id" id="user_id" class="form-control">
            </div>
          </div>
        </div>
        <div class="card-body">
          <button class="btn btn-primary">新規登録</button>
        </div>
      </div>
    </form>
<?= $this->fetch('footer.phtml') ?>
